<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Bitly' => array($vendorDir . '/kananlanginhooper/bitly-api-php/src'),
);
